=== s1dekick101/cs598-assignment2/Part1/cellphone.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="Billing">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Phonebill">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="invoiceDate">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:int" name="timestamp"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="invoiceNumber">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="previousCharges">
                      <xs:complexType>
                        <xs:sequence>
							<xs:restriction base="xs:float">
							  <xs:element type="xs:float" name="previousAccountBalance"/>
							  <xs:element type="xs:float" name="paymentsRecieved"/>
							  <xs:element type="xs:float" name="otherChargesandCredits"/>
							  <xs:element type="xs:float" name="balanceForward"/>
							</xs:restriction>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="newCharges">
                      <xs:complexType>
                        <xs:sequence>
							<xs:restriction base="xs:float">
							  <xs:element type="xs:float" name="wireless"/>
							  <xs:element type="xs:float" name="longDistance"/>
							  <xs:element type="xs:float" name="Internet"/>
							  <xs:element type="xs:float" name="currentInstallmentsDue"/>
							  <xs:element type="xs:float" name="otherNewAccountCharges"/>
							  <xs:element type="xs:float" name="newChargesBalance"/>
							</xs:restriction>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="pastDueAmmount">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:float" name="prevAmount"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="totalAmountDue">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:float" name="currAmount"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:int" name="uniqueID"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="customerInformation">
                <xs:complexType>
                  <xs:sequence>
					<xs:restriction base="xs:string">
						<xs:element type="xs:string" name="firstName"/>
						<xs:element type="xs:string" name="lastName"/>
						<xs:element type="xs:string" name="street"/>
						<xs:element type="xs:string" name="city"/>
						<xs:element type="xs:string" name="state"/>
					</xs:restriction>
					<xs:restriction base="xs:int">
						<xs:element type="xs:int" name="zipCode"/>
					</xs:restriction>
                    <xs:element name="accountNumber">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:int" name="customerID"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="CompanyContactInformation">
                <xs:complexType>
                  <xs:sequence>
					<xs:restriction base="xs:string">
						<xs:element type="xs:string" name="companyName"/>
						<xs:element type="xs:string" name="street"/>
						<xs:element type="xs:string" name="unitNumber"/>
						<xs:element type="xs:string" name="city"/>
						<xs:element type="xs:string" name="state"/>
						<xs:element type="xs:string" name="phone"/>
						<xs:element type="xs:string" name="fax"/>
						<xs:element type="xs:string" name="email"/>
					</xs:restriction>
					<xs:restriction base="xs:int">
						<xs:element type="xs:int" name="zipCode"/>
					</xs:restriction>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== s1dekick101/cs598-assignment2/Part1/cellphone.xml
<?xml version="1.0" encoding="UTF-8"?>
<Billing
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://github.com/s1dekick101/cs598-assignment2/blob/main/Part1/cellphone.xsd">
	
	
	<Phonebill>
		<invoiceDate timestamp="07012011"></invoiceDate>
		<invoiceNumber uniqueID="004194129">
			<previousCharges>
				<previousAccountBalance>86.26</previousAccountBalance>
				<paymentsRecieved>0.00</paymentsRecieved>
				<otherChargesandCredits>1.67</otherChargesandCredits>
				<balanceForward>86.26</balanceForward>
			</previousCharges>
			<newCharges>
				<wireless>86.52</wireless>
				<longDistance>20.00</longDistance>
				<Internet>103.00</Internet>
				<currentInstallmentsDue>350.00</currentInstallmentsDue>
				<otherNewAccountCharges>1.67</otherNewAccountCharges>
				<newChargesBalance>561.19</newChargesBalance>
			</newCharges>
			<pastDueAmmount prevAmount="86.26"></pastDueAmmount>
			<totalAmountDue currAmount="561.19"></totalAmountDue>
		</invoiceNumber>
		<customerInformation>
			<firstName>Steve</firstName>
			<lastName>Luke</lastName>
			<street>1245 Main Street</street>
			<city>Duluth</city>
			<state>GA</state>
			<zipCode>30096</zipCode>
			<accountNumber customerID="00001719228"></accountNumber>
		</customerInformation>
		<CompanyContactInformation>
			<companyName>Advantage 360</companyName>
			<street>10681 Foothill Blvd</street>
			<unitNumber>Suite 100</unitNumber>
			<city>Rancho Cucamonga</city>
			<state>CA</state>
			<phone>+1 909 980-1034 </phone>
			<fax>+1 909 944-3995</fax>
			<email>sales@advantage360.com</email>
			<zipCode>91730</zipCode>
		</CompanyContactInformation>
	</Phonebill>
</Billing>
